-- ============================================================
-- RLS Policies for fs_orders and fs_order_items
-- Users can only read their own orders/items.
-- Edge Functions use service_role key (bypasses RLS) to write.
-- ============================================================

-- Enable RLS on fs_orders
ALTER TABLE fs_orders ENABLE ROW LEVEL SECURITY;

-- Users can read only their own orders (matched by email from auth.jwt())
CREATE POLICY "Users can read own orders"
  ON fs_orders
  FOR SELECT
  USING (
    email = (auth.jwt() ->> 'email')
  );

-- Enable RLS on fs_order_items
ALTER TABLE fs_order_items ENABLE ROW LEVEL SECURITY;

-- Users can read items of their own orders
CREATE POLICY "Users can read own order items"
  ON fs_order_items
  FOR SELECT
  USING (
    order_id IN (
      SELECT id FROM fs_orders WHERE email = (auth.jwt() ->> 'email')
    )
  );

-- ============================================================
-- Storage bucket for invoices
-- ============================================================

-- Create the invoices bucket (private by default)
INSERT INTO storage.buckets (id, name, public)
VALUES ('invoices', 'invoices', false)
ON CONFLICT (id) DO NOTHING;

-- Users can read their own invoices via signed URLs (generated by Edge Function)
-- No direct user access needed — Edge Functions use service_role.
-- If you want users to also read directly:
-- CREATE POLICY "Users can read own invoices"
--   ON storage.objects
--   FOR SELECT
--   USING (
--     bucket_id = 'invoices'
--     AND (storage.foldername(name))[1] = 'invoices'
--   );

-- ============================================================
-- Ensure fs_orders has needed columns (idempotent)
-- ============================================================

-- Add stripe columns if they don't exist
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'fs_orders' AND column_name = 'stripe_session_id'
  ) THEN
    ALTER TABLE fs_orders ADD COLUMN stripe_session_id text;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'fs_orders' AND column_name = 'stripe_payment_intent'
  ) THEN
    ALTER TABLE fs_orders ADD COLUMN stripe_payment_intent text;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'fs_orders' AND column_name = 'invoice_token'
  ) THEN
    ALTER TABLE fs_orders ADD COLUMN invoice_token text;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'fs_orders' AND column_name = 'paid_at'
  ) THEN
    ALTER TABLE fs_orders ADD COLUMN paid_at timestamptz;
  END IF;
END $$;
